coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: true
    patch: true
    changes: true

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default